version: "3"

services: 
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=myapp
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./db:/var/lib/mysql